FROM public.ecr.aws/nginx/nginx:1.27-alpine3.21-slim

# 将你的 Nginx 配置文件复制到容器中
COPY nginx.conf /etc/nginx/conf.d/default.conf

# 将你的 client 文件夹复制到容器中
COPY client /usr/share/nginx/html

# 暴露 80 端口
EXPOSE 80

# 启动 Nginx
CMD ["nginx", "-g", "daemon off;"]
